package com.vconsulte.sij.base;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class Parametros {
	
	public static final String USUARIO 					= "sgj";
    public static final String PASSWORD 				= "934769386";
    public static final String TIPODOCUMENTO 			= "publicacao";
    
    public static final String VERSAOSPLITER 			= "v2.3.21c";
    
    public static final String FONTSIZE 				= "9";
    public static final String FONT 					= "HELVETICA";
    public static final String FONTCOLOR 				= "BLUE";
    
    public static String URL 							= "";	
    public static String CLIENTE 						= "V&C Consultoria Ltda";			
    public static String TIPOSAIDA 						= "TEXTO";						
    public static String SYSOP 							= "LINUX";
    public static String LOGFOLDER 						= "";
    public static String PASTABASE 						= "/Sites/advocacia/documentLibrary/secretaria/carregamento";
    public static String PASTAINDEXADOS 				= "/Sites/advocacia/documentLibrary/secretaria/publicacoes";
    
    public static List <String> TABELAUTORES = new ArrayList<String>();
    public static List <String> JURIDIQUES = new ArrayList<String>();
    public static List <String> FALSOFINAL = new ArrayList<String>();
    public static List <String> STOPWORDS = new ArrayList<String>();
    public static List <String> KEYWORDS = new ArrayList<String>();
    public static List <String> FUNCOES = new ArrayList<String>();
    public static List <String> CONTINUADORES = new ArrayList<String>();
    public static List <String> FORMATODATAS = new ArrayList<String>();
    public static List <String> MESES = new ArrayList<String>();

	public static void carregaTabelas() { 
		
		MESES.add("janeiro"); MESES.add("fevereiro"); MESES.add("marco"); 
		MESES.add("abril"); MESES.add("maio"); MESES.add("junho");
		MESES.add("julho"); MESES.add("agosto"); MESES.add("setembro");
		MESES.add("outubro"); MESES.add("novembro"); MESES.add("dezembro");

		CONTINUADORES.add("ao"); CONTINUADORES.add("como"); CONTINUADORES.add("e");
		CONTINUADORES.add("da"); CONTINUADORES.add("das"); CONTINUADORES.add("de");
		CONTINUADORES.add("desse"); CONTINUADORES.add("desses"); CONTINUADORES.add("deste");
		CONTINUADORES.add("destes"); CONTINUADORES.add("nos"); CONTINUADORES.add("-");
		
		FUNCOES.add("chefe da secretaria"); FUNCOES.add("desembargadora relatora"); FUNCOES.add("desembargadora");
		FUNCOES.add("desembargador relator"); FUNCOES.add("desembargador"); FUNCOES.add("desembargador(a)");
		FUNCOES.add("desembargador(a) vice presidente judicial"); FUNCOES.add("desembargador vice presidente judicial");
		FUNCOES.add("desembargadora vice presidente judicial"); FUNCOES.add("diretor de secretaria");
		FUNCOES.add("diretora de secretaria"); FUNCOES.add("juiza titular"); FUNCOES.add("juiz titular");
		FUNCOES.add("juiz(a) do trabalho titular"); FUNCOES.add("juiza do trabalho titular");
		FUNCOES.add("juiz do trabalho titular"); 
		FUNCOES.add("secretaria"); FUNCOES.add("tecnico judiciario");
		
		TABELAUTORES.add("advogado"); TABELAUTORES.add("advogados");  TABELAUTORES.add("agravado");
        TABELAUTORES.add("agravados"); TABELAUTORES.add("agravante"); TABELAUTORES.add("agravantes");
        TABELAUTORES.add("autor"); TABELAUTORES.add("autores"); TABELAUTORES.add("autoridade coatora");
        TABELAUTORES.add("consignante"); TABELAUTORES.add("consignantes"); TABELAUTORES.add("consignatario");
        TABELAUTORES.add("consignatarios"); TABELAUTORES.add("custos legais"); TABELAUTORES.add("custos legis");
        TABELAUTORES.add("decimo interessado"); TABELAUTORES.add("exequente"); TABELAUTORES.add("exequentes");
        TABELAUTORES.add("executado"); TABELAUTORES.add("executados"); TABELAUTORES.add("impetrante");
        TABELAUTORES.add("impetrantes"); TABELAUTORES.add("impetrado");  TABELAUTORES.add("impetrados");
        TABELAUTORES.add("juizo recorrente"); TABELAUTORES.add("orgao julgador"); TABELAUTORES.add("perito");
        TABELAUTORES.add("peritos");
        TABELAUTORES.add("reclamante");
        TABELAUTORES.add("reclamado");
        TABELAUTORES.add("reclamados");
        TABELAUTORES.add("recorrido");
        TABELAUTORES.add("recorridos");
        TABELAUTORES.add("recorrente");
        TABELAUTORES.add("recorrentes");
        TABELAUTORES.add("requerente");
        TABELAUTORES.add("requerentes");
        TABELAUTORES.add("requerido");
        TABELAUTORES.add("requeridos");
        TABELAUTORES.add("relator");
        TABELAUTORES.add("relatores");
        TABELAUTORES.add("reu");
        TABELAUTORES.add("res");
        TABELAUTORES.add("revisor");
        TABELAUTORES.add("revisores");
        TABELAUTORES.add("solicitado");
        TABELAUTORES.add("solicitados");
        TABELAUTORES.add("solicitante");
        TABELAUTORES.add("solicitantes");
        TABELAUTORES.add("polo ativo");
        TABELAUTORES.add("polo passivo");
        TABELAUTORES.add("primeiro interessado");
        TABELAUTORES.add("procedencia");
        TABELAUTORES.add("segundo interessado");
        TABELAUTORES.add("terceiro interessado");
        TABELAUTORES.add("testemunha");
        TABELAUTORES.add("quarto interessado");
        TABELAUTORES.add("quinto interessado");
        TABELAUTORES.add("sexto interessado");
        TABELAUTORES.add("setimo interessado");
        TABELAUTORES.add("oitavo interessado");
        TABELAUTORES.add("nono interessado");

        KEYWORDS.add("1.");
		KEYWORDS.add("2.");
		KEYWORDS.add("3.");
		KEYWORDS.add("4.");
		KEYWORDS.add("5.");
		KEYWORDS.add("6.");
		KEYWORDS.add("7.");
		KEYWORDS.add("8.");
		KEYWORDS.add("9.");
		KEYWORDS.add("0.");
    	KEYWORDS.add("artigo");
    	KEYWORDS.add("advogado");
    	KEYWORDS.add("advogados");
    	KEYWORDS.add("cartorio");
    	KEYWORDS.add("cartorios");
    	KEYWORDS.add("clt");
    	KEYWORDS.add("codigo");
    	KEYWORDS.add("codigos");
    	KEYWORDS.add("colegiado");
    	KEYWORDS.add("colegiados");
    	KEYWORDS.add("defesa");
    	KEYWORDS.add("empregado");
    	KEYWORDS.add("empregador");
    	KEYWORDS.add("empregadores");
    	KEYWORDS.add("empregados");
    	KEYWORDS.add("empresa");
    	KEYWORDS.add("empresas");
    	KEYWORDS.add("evidencias");
    	KEYWORDS.add("evidencia");
    	KEYWORDS.add("funcionario");
    	KEYWORDS.add("funcionarios");
    	KEYWORDS.add("inciso");
    	KEYWORDS.add("interessado");
    	KEYWORDS.add("interessados");
		KEYWORDS.add("intimado");
		KEYWORDS.add("intimados");
		KEYWORDS.add("indenizacao");
		KEYWORDS.add("indenizacoes");
		KEYWORDS.add("judiciario");
		KEYWORDS.add("julgamento");
		KEYWORDS.add("julgamentos");
		KEYWORDS.add("julgado");
		KEYWORDS.add("julgados");
		KEYWORDS.add("juiz");
		KEYWORDS.add("juizes");
		KEYWORDS.add("ministerio");
		KEYWORDS.add("ministerios");
		KEYWORDS.add("membro");
		KEYWORDS.add("membros");
		KEYWORDS.add("oral");
		KEYWORDS.add("ordinaria");
		KEYWORDS.add("pagina");
		KEYWORDS.add("paginas");
		KEYWORDS.add("pauta");
		KEYWORDS.add("pautas");
		KEYWORDS.add("pedido");
		KEYWORDS.add("pedidos");
		KEYWORDS.add("penal");
		KEYWORDS.add("penais");
		KEYWORDS.add("pje");
		KEYWORDS.add("presencial");
		KEYWORDS.add("procedencia");
		KEYWORDS.add("processos");
		KEYWORDS.add("processo");
		KEYWORDS.add("prova");
		KEYWORDS.add("provas");
		KEYWORDS.add("publicacao");
		KEYWORDS.add("publicacoes");
		KEYWORDS.add("publico");
		KEYWORDS.add("regional");
		KEYWORDS.add("remoto");
		KEYWORDS.add("resolucao");
		KEYWORDS.add("tecnico");
		KEYWORDS.add("trabalho");
		KEYWORDS.add("trabalhista");
		KEYWORDS.add("tribunal");
		KEYWORDS.add("trt");
		KEYWORDS.add("tst");
		KEYWORDS.add("vara");
		KEYWORDS.add("varas");
		KEYWORDS.add("primeiro");
        KEYWORDS.add("segundo");
        KEYWORDS.add("terceiro");
        KEYWORDS.add("quarto");
        KEYWORDS.add("quinto");
        KEYWORDS.add("sexto");
        KEYWORDS.add("setimo");
        KEYWORDS.add("oitavo");
        KEYWORDS.add("nono");
        KEYWORDS.add("decimo");
        KEYWORDS.add("pernambuco");
		KEYWORDS.add("rio");
		KEYWORDS.add("janeiro");
		KEYWORDS.add("sao paulo");
		KEYWORDS.add("amazonas");
		KEYWORDS.add("para");
		KEYWORDS.add("piaui");
		KEYWORDS.add("maranhao");
		KEYWORDS.add("ceara");
		KEYWORDS.add("grande");
		KEYWORDS.add("norte");
		KEYWORDS.add("sul");
		KEYWORDS.add("parana");
		KEYWORDS.add("supremo");
		KEYWORDS.add("santa catarina");
		KEYWORDS.add("tocantins");
		KEYWORDS.add("mato grosso");
		KEYWORDS.add("mato grosso do sul");
		KEYWORDS.add("goias");
		KEYWORDS.add("espirito");
		KEYWORDS.add("santo");
		KEYWORDS.add("paraiba");
		KEYWORDS.add("alagoas");
		KEYWORDS.add("sergipe");
		KEYWORDS.add("bahia");
		KEYWORDS.add("acre");
		KEYWORDS.add("rondonia");
		KEYWORDS.add("roraima");
		KEYWORDS.add("brasilia");
		KEYWORDS.add("fevereiro");
		KEYWORDS.add("marco");
		KEYWORDS.add("abril");
		KEYWORDS.add("maio");
		KEYWORDS.add("junho");
		KEYWORDS.add("julho");
		KEYWORDS.add("agosto");
		KEYWORDS.add("setembro");
		KEYWORDS.add("outubro");
		KEYWORDS.add("novembro");
		KEYWORDS.add("dezembro");
		KEYWORDS.add("ac");
		KEYWORDS.add("al");
		KEYWORDS.add("am");
		KEYWORDS.add("ap");
		KEYWORDS.add("ba");
		KEYWORDS.add("ce");
		KEYWORDS.add("df");
		KEYWORDS.add("es");
		KEYWORDS.add("go");
		KEYWORDS.add("ma");
		KEYWORDS.add("mg");
		KEYWORDS.add("ms");
		KEYWORDS.add("mt");
		KEYWORDS.add("pa");
		KEYWORDS.add("pb");
		KEYWORDS.add("pe");
		KEYWORDS.add("pi");
		KEYWORDS.add("pr");
		KEYWORDS.add("rj");
		KEYWORDS.add("rn");
		KEYWORDS.add("ro");
		KEYWORDS.add("rr");
		KEYWORDS.add("rs");
		KEYWORDS.add("sc");
		KEYWORDS.add("se");
		KEYWORDS.add("sp");
		KEYWORDS.add("to");
        
        JURIDIQUES.add("acao");
        JURIDIQUES.add("acoes");
        JURIDIQUES.add("acao concentrada");
        JURIDIQUES.add("acoes concentradas");
        JURIDIQUES.add("agravo");
        JURIDIQUES.add("agravos");
        JURIDIQUES.add("agravo de instrumento");
        JURIDIQUES.add("agravos de instrumentos");
        JURIDIQUES.add("agravo regimental");
        JURIDIQUES.add("agravos regimentais");
        JURIDIQUES.add("alegacoes");
        JURIDIQUES.add("assinatura");
        JURIDIQUES.add("atraso no pagamento dos salarios");
		JURIDIQUES.add("certidao de julgamento");
		JURIDIQUES.add("ciencia");
		JURIDIQUES.add("coisa julgada");
		JURIDIQUES.add("conclusao");
		JURIDIQUES.add("conexao e continencia");
		JURIDIQUES.add("consideracoes preliminares");
		JURIDIQUES.add("contestacao");
		JURIDIQUES.add("continencia");
		JURIDIQUES.add("da admissibilidade");
		JURIDIQUES.add("danos morais");
		JURIDIQUES.add("danos morais nao configurados");
		JURIDIQUES.add("das gorjetas");
		JURIDIQUES.add("das preliminares");
		JURIDIQUES.add("deposito em garantia do juizo");
		JURIDIQUES.add("despacho");
		JURIDIQUES.add("direito do trabalho");
		JURIDIQUES.add("do merito");
		JURIDIQUES.add("dos embargos do reclamado");
		JURIDIQUES.add("dos embargos do reclamante");
		JURIDIQUES.add("do recurso ordinario da reclamante");
		JURIDIQUES.add("do recurso ordinario da reclamado");
		JURIDIQUES.add("edital de intimacao em processo eletronico");
		JURIDIQUES.add("edital de notificacao da secretaria do tribunal pleno");
		JURIDIQUES.add("ementa");
		JURIDIQUES.add("ementa:");
		JURIDIQUES.add("empregado");
		JURIDIQUES.add("empregados");
		JURIDIQUES.add("empregador");
		JURIDIQUES.add("empregadores");
		JURIDIQUES.add("excecoes");
		JURIDIQUES.add("execucao");
		JURIDIQUES.add("execucoes");	
		JURIDIQUES.add("fgts");
		JURIDIQUES.add("fundamentacao");
		JURIDIQUES.add("hora extra");
		JURIDIQUES.add("horas extras");
		JURIDIQUES.add("indenizacao");
		JURIDIQUES.add("indenizacao indevida");
		JURIDIQUES.add("indevida a indenizacao");
		JURIDIQUES.add("inepcia");
		JURIDIQUES.add("inepcia da inicial");
		JURIDIQUES.add("intimacao");
		JURIDIQUES.add("ipca");
		JURIDIQUES.add("inpc");
		JURIDIQUES.add("julgador");
		JURIDIQUES.add("julgadores");
		JURIDIQUES.add("judiciario");
		JURIDIQUES.add("juros de mora");
		JURIDIQUES.add("justica do trabalho");
		JURIDIQUES.add("litispendencia");
		JURIDIQUES.add("nota sessao de julgamento virtual");
		JURIDIQUES.add("merito");
		JURIDIQUES.add("nulidade de citacao");
		JURIDIQUES.add("orgao julgador");
		JURIDIQUES.add("poder");
		JURIDIQUES.add("poder judiciario");
		JURIDIQUES.add("preliminar");
		JURIDIQUES.add("pressupostos extrinsecos");
		JURIDIQUES.add("pressupostos intrinsecos");
		JURIDIQUES.add("prova");
		JURIDIQUES.add("provas");
		JURIDIQUES.add("provimento");
		JURIDIQUES.add("provimentos");
		JURIDIQUES.add("reconvencao");
		JURIDIQUES.add("recurso");
		JURIDIQUES.add("recursos");
		JURIDIQUES.add("recurso adesivo do reclamante");
		JURIDIQUES.add("recurso adesivo da reclamante");
		JURIDIQUES.add("recurso da reclamada");
		JURIDIQUES.add("recurso do reclamado");
		JURIDIQUES.add("recurso de revista");
		JURIDIQUES.add("recurso ordinario");
		JURIDIQUES.add("recursos ordinarios");
		JURIDIQUES.add("recurso ordinario obreiro");
		JURIDIQUES.add("recesso");
		JURIDIQUES.add("recisao");
		JURIDIQUES.add("secao de recursos");
		JURIDIQUES.add("sentenca");
		JURIDIQUES.add("trabalho");
		JURIDIQUES.add("trt");
		JURIDIQUES.add("tst");
		JURIDIQUES.add("vinculo empregaticio");
		JURIDIQUES.add("vara");
		JURIDIQUES.add("varas");
		JURIDIQUES.add("voto");
		JURIDIQUES.add("votos");
		JURIDIQUES.add("resolucoes");
		JURIDIQUES.add("reu");
		JURIDIQUES.add("sessao");
		JURIDIQUES.add("sentenca");
		JURIDIQUES.add("sustentacao");
		
		FALSOFINAL.add("ltda.");
		FALSOFINAL.add("a/a.");
		FALSOFINAL.add("v. sa.");
		FALSOFINAL.add("v.sa.");
		FALSOFINAL.add("arts.");
		FALSOFINAL.add("CLT.");
		FALSOFINAL.add("pag.");
		FALSOFINAL.add("art.");
		FALSOFINAL.add("inc.");
		FALSOFINAL.add("v.");
		
		STOPWORDS.add("a");
		STOPWORDS.add("e");
		STOPWORDS.add("o");
		STOPWORDS.add("as");
		STOPWORDS.add("os");
		STOPWORDS.add("na");
		STOPWORDS.add("no");
		STOPWORDS.add("da");
		STOPWORDS.add("de");
		STOPWORDS.add("do");
		STOPWORDS.add("mas");
		STOPWORDS.add("mais");
		STOPWORDS.add("porem");
		STOPWORDS.add("entretanto");
		STOPWORDS.add("de");
		STOPWORDS.add("ele");
		STOPWORDS.add("num");
		STOPWORDS.add("delas");
		STOPWORDS.add("houveramos");
		STOPWORDS.add("seremos");
		STOPWORDS.add("qualquer");
		STOPWORDS.add("assim");
		STOPWORDS.add("das");
		STOPWORDS.add("nem");
		STOPWORDS.add("esta");
		STOPWORDS.add("haja");
		STOPWORDS.add("serao");
		STOPWORDS.add("cada");
		STOPWORDS.add("afim");
		STOPWORDS.add("tem");
		STOPWORDS.add("suas");
		STOPWORDS.add("estes");
		STOPWORDS.add("hajamos");
		STOPWORDS.add("seria");
		STOPWORDS.add("apos");
		STOPWORDS.add("agora");
		STOPWORDS.add("meu");
		STOPWORDS.add("estas");
		STOPWORDS.add("hajam");
		STOPWORDS.add("seriamos");
		STOPWORDS.add("durante");
		STOPWORDS.add("onde");
		STOPWORDS.add("seu");
		STOPWORDS.add("as");
		STOPWORDS.add("aquele");
		STOPWORDS.add("houvesse");
		STOPWORDS.add("seriam");
		STOPWORDS.add("entanto");
		STOPWORDS.add("outro");
		STOPWORDS.add("sua");
		STOPWORDS.add("minha");
		STOPWORDS.add("aquela");
		STOPWORDS.add("houvessemos");
		STOPWORDS.add("tenho");
		STOPWORDS.add("sempre");
		STOPWORDS.add("outros");
		STOPWORDS.add("ou");
		STOPWORDS.add("tem");
		STOPWORDS.add("aqueles");
		STOPWORDS.add("houvessem");
		STOPWORDS.add("tem");
		STOPWORDS.add("menos");
		STOPWORDS.add("ainda");
		STOPWORDS.add("ser");
		STOPWORDS.add("numa");
		STOPWORDS.add("aquelas");
		STOPWORDS.add("houver");
		STOPWORDS.add("temos");
		STOPWORDS.add("mais");
		STOPWORDS.add("a");
		STOPWORDS.add("quando");
		STOPWORDS.add("pelos");
		STOPWORDS.add("isto");
		STOPWORDS.add("houvermos");
		STOPWORDS.add("tem");
		STOPWORDS.add("caso");
		STOPWORDS.add("o");
		STOPWORDS.add("muito");
		STOPWORDS.add("elas");
		STOPWORDS.add("aquilo");
		STOPWORDS.add("houverem");
		STOPWORDS.add("tinha");
		STOPWORDS.add("segundo");
		STOPWORDS.add("que");
		STOPWORDS.add("ha");
		STOPWORDS.add("havia");
		STOPWORDS.add("estou");
		STOPWORDS.add("houverei");
		STOPWORDS.add("tinhamos");
		STOPWORDS.add("aqueles");
		STOPWORDS.add("vario");
		STOPWORDS.add("nos");
		STOPWORDS.add("seja");
		STOPWORDS.add("esta");
		STOPWORDS.add("houvera");
		STOPWORDS.add("houve");
		STOPWORDS.add("houveram");
		STOPWORDS.add("houverao");
		STOPWORDS.add("tinham");
		STOPWORDS.add("destas");
		STOPWORDS.add("desta");
		STOPWORDS.add("destes");
		STOPWORDS.add("dezessete");
		STOPWORDS.add("varios");
		STOPWORDS.add("ja");
		STOPWORDS.add("qual");
		STOPWORDS.add("estamos");
		STOPWORDS.add("houveremos");
		STOPWORDS.add("houver");
		STOPWORDS.add("houveriamos");
		STOPWORDS.add("tive");
		STOPWORDS.add("todos");
		STOPWORDS.add("vario");
		STOPWORDS.add("varios");
		STOPWORDS.add("varias");
		STOPWORDS.add("esta");
		STOPWORDS.add("sera");
		STOPWORDS.add("estão");
		STOPWORDS.add("houverao");
		STOPWORDS.add("teve");
		STOPWORDS.add("varios");
		STOPWORDS.add("eu");
		STOPWORDS.add("nos");
		STOPWORDS.add("estive");
		STOPWORDS.add("houveria");
		STOPWORDS.add("tivemos");
		STOPWORDS.add("e");
		STOPWORDS.add("tambem");
		STOPWORDS.add("tenho");
		STOPWORDS.add("esteve");
		STOPWORDS.add("houveriamos");
		STOPWORDS.add("tiveram");
		STOPWORDS.add("do");
		STOPWORDS.add("so");
		STOPWORDS.add("lhe");
		STOPWORDS.add("estivemos");
		STOPWORDS.add("houveriam");
		STOPWORDS.add("tivera");
		STOPWORDS.add("da");
		STOPWORDS.add("pelo");
		STOPWORDS.add("deles");
		STOPWORDS.add("estiveram ");
		STOPWORDS.add("sou");
		STOPWORDS.add("tiveramos");
		STOPWORDS.add("uns");
		STOPWORDS.add("pela ");
		STOPWORDS.add("essas");
		STOPWORDS.add("estava");
		STOPWORDS.add("somos");
		STOPWORDS.add("tenha");
		STOPWORDS.add("em");
		STOPWORDS.add("ate");
		STOPWORDS.add("esses");
		STOPWORDS.add("estavamos");
		STOPWORDS.add("sao");
		STOPWORDS.add("tenhamos");
		STOPWORDS.add("um");
		STOPWORDS.add("isso");
		STOPWORDS.add("pelas");
		STOPWORDS.add("estavam");
		STOPWORDS.add("era");
		STOPWORDS.add("tenham");
		STOPWORDS.add("para");
		STOPWORDS.add("ela");
		STOPWORDS.add("este");
		STOPWORDS.add("estivera");
		STOPWORDS.add("eramos");
		STOPWORDS.add("tivesse");
		STOPWORDS.add("e");
		STOPWORDS.add("entre");
		STOPWORDS.add("fosse");
		STOPWORDS.add("estiveramos");
		STOPWORDS.add("eram");
		STOPWORDS.add("tivessemos");
		STOPWORDS.add("antes");
		STOPWORDS.add("era");
		STOPWORDS.add("dele");
		STOPWORDS.add("esteja");
		STOPWORDS.add("fui");
		STOPWORDS.add("tivessem");
		STOPWORDS.add("anti");
		STOPWORDS.add("depois");
		STOPWORDS.add("tu");
		STOPWORDS.add("estejamos");
		STOPWORDS.add("foi");
		STOPWORDS.add("tiver");
		STOPWORDS.add("com");
		STOPWORDS.add("sem ");
		STOPWORDS.add("te"); 
		STOPWORDS.add("estejam"); 
		STOPWORDS.add("fomos");
		STOPWORDS.add("tivermos");
		STOPWORDS.add("não");
		STOPWORDS.add("mesmo"); 
		STOPWORDS.add("vocês"); 
		STOPWORDS.add("estivesse"); 
		STOPWORDS.add("foram"); 
		STOPWORDS.add("tiverem");
		STOPWORDS.add("uma"); 
		STOPWORDS.add("aos"); 
		STOPWORDS.add("vos"); 
		STOPWORDS.add("estivéssemos"); 
		STOPWORDS.add("fora");
		STOPWORDS.add("terei");
		STOPWORDS.add("os"); 
		STOPWORDS.add("ter");
		STOPWORDS.add("lhes");
		STOPWORDS.add("estivessem"); 
		STOPWORDS.add("foramos"); 
		STOPWORDS.add("tera");
		STOPWORDS.add("no");
		STOPWORDS.add("seus"); 
		STOPWORDS.add("meus"); 
		STOPWORDS.add("estiver"); 
		STOPWORDS.add("seja"); 
		STOPWORDS.add("teremos");
		STOPWORDS.add("se"); 
		STOPWORDS.add("quem");
		STOPWORDS.add("minhas"); 
		STOPWORDS.add("estivermos"); 
		STOPWORDS.add("sejamos"); 
		STOPWORDS.add("terao");
		STOPWORDS.add("na");
		STOPWORDS.add("nas"); 
		STOPWORDS.add("teu"); 
		STOPWORDS.add("estiverem"); 
		STOPWORDS.add("sejam"); 
		STOPWORDS.add("teria");
		STOPWORDS.add("por"); 
		STOPWORDS.add("me"); 
		STOPWORDS.add("tua"); 
		STOPWORDS.add("hei"); 
		STOPWORDS.add("fosse"); 
		STOPWORDS.add("teriamos");
		STOPWORDS.add("mais"); 
		STOPWORDS.add("esse"); 
		STOPWORDS.add("teus"); 
		STOPWORDS.add("ha"); 
		STOPWORDS.add("fossemos"); 
		STOPWORDS.add("teriam");
		STOPWORDS.add("as"); 
		STOPWORDS.add("eles"); 
		STOPWORDS.add("tuas"); 
		STOPWORDS.add("havemos"); 
		STOPWORDS.add("fossem"); 
		STOPWORDS.add("porem");
		STOPWORDS.add("dos"); 
		STOPWORDS.add("estao"); 
		STOPWORDS.add("nosso"); 
		STOPWORDS.add("hao"); 
		STOPWORDS.add("for"); 
		STOPWORDS.add("todavia");
		STOPWORDS.add("como");
		STOPWORDS.add("voce");
		STOPWORDS.add("nossa"); 
		STOPWORDS.add("houve"); 
		STOPWORDS.add("formos"); 
		STOPWORDS.add("entretanto");
		STOPWORDS.add("mas"); 
		STOPWORDS.add("tinha"); 
		STOPWORDS.add("nossos"); 
		STOPWORDS.add("houvemos"); 
		STOPWORDS.add("forem"); 
		STOPWORDS.add("contudo");
		STOPWORDS.add("foi"); 
		STOPWORDS.add("foram"); 
		STOPWORDS.add("nossas"); 
		STOPWORDS.add("houveram");
		STOPWORDS.add("serei"); 
		STOPWORDS.add("quer");
		STOPWORDS.add("ao"); 
		STOPWORDS.add("essa"); 
		STOPWORDS.add("dela"); 
		STOPWORDS.add("houvera");
		STOPWORDS.add("sera"); 
		STOPWORDS.add("quais");
		
		// - Formatos de datas
		// dd/mm/aaaa
		FORMATODATAS.add("(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/(19|20)\\d{2}");			// dd/mm/aaaa
		
		//aaaammdd
		FORMATODATAS.add("\"^(?:(?:(?:(?:[13579][26]|[2468][048])00)|(?:[0-9]{2}(?:(?:[13579][26])|(?:[2468][048]|0[48]))))(?:(?:(?:09|04|06|11)(?:0[1-9]|1[0-9]|2[0-9]|30))|(?:(?:01|03|05|07|08|10|12)(?:0[1-9]|1[0-9]|2[0-9]|3[01]))|(?:02(?:0[1-9]|1[0-9]|2[0-9]))))|(?:[0-9]{4}(?:(?:(?:09|04|06|11)(?:0[1-9]|1[0-9]|2[0-9]|30))|(?:(?:01|03|05|07|08|10|12)(?:0[1-9]|1[0-9]|2[0-9]|3[01]))|(?:02(?:[01][0-9]|2[0-8]))))$\"");
		
		//dd/mm/aaaa
		FORMATODATAS.add("^(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)(?:0?[1,3-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$");
	}
    
}